create table MEAL_SHOPPING_LIST
(
    MEAL_ID UUID REFERENCES MEAL(ID) ON UPDATE CASCADE ON DELETE CASCADE,
    SHOPPING_LIST_ID UUID REFERENCES SHOPPING_LIST(ID) ON UPDATE CASCADE ON DELETE CASCADE
);